"use client";

/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { LuArrowRight as ArrowRight, LuMinus as Minus, LuPlus as Plus, LuShieldCheck as Shield, LuShoppingBag as Bag, LuTrash2 as Trash } from "react-icons/lu";
import { useCurrency } from "@/hooks/useCurrency";
import { useTravelStore } from "@/providers/TravelStoreProvider";

export default function CartPage() {
  const { hydrated, cart, removeFromCart, updateTravellers, clearCart } = useTravelStore();
  const { format, convert, code } = useCurrency();
  const estimatedTotal = cart.reduce((total, item) => total + convert(item.price || 0, item.currency) * item.travellers, 0);
  return (
    <main className="min-h-screen bg-slate-50 pb-20 pt-28">
      <section className="mx-auto max-w-7xl px-5 md:px-8">
        <div className="flex items-end justify-between border-b border-slate-200 pb-7"><div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Review your choices</p><h1 className="mt-2 text-4xl font-black tracking-tight text-slate-950">Your cart</h1><p className="mt-2 text-sm text-slate-500">Confirm each tour and continue to its secure booking flow.</p></div>{cart.length > 0 && <button type="button" onClick={clearCart} className="text-xs font-bold text-slate-400 hover:text-red-500">Clear cart</button>}</div>
        {!hydrated ? <div className="mt-8 h-80 animate-pulse rounded-2xl bg-slate-200" /> : cart.length === 0 ? <EmptyCart /> : <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px] lg:items-start"><div className="space-y-4">{cart.map((item) => <article key={item.id} className="grid overflow-hidden rounded-2xl border border-slate-100 bg-white p-3 shadow-sm sm:grid-cols-[190px_1fr]"><Link href={`/tours/${item.id}`} className="h-44 overflow-hidden rounded-xl"><img src={item.image} alt={item.title} className="h-full w-full object-cover transition duration-500 hover:scale-105" /></Link><div className="flex flex-col p-3 sm:px-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold text-blue-600">{item.place} · {item.duration}</p><Link href={`/tours/${item.id}`} className="mt-1 block text-lg font-black hover:text-blue-600">{item.title}</Link></div><button type="button" onClick={() => removeFromCart(item.id)} aria-label={`Remove ${item.title}`} className="text-slate-300 hover:text-red-500"><Trash size={16} /></button></div><div className="mt-auto flex flex-wrap items-end justify-between gap-4 pt-5"><div><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Travellers</p><div className="mt-1 flex items-center rounded-lg border border-slate-200"><button type="button" onClick={() => updateTravellers(item.id, item.travellers - 1)} className="flex h-8 w-8 items-center justify-center"><Minus size={12} /></button><b className="w-8 text-center text-xs">{item.travellers}</b><button type="button" onClick={() => updateTravellers(item.id, item.travellers + 1)} className="flex h-8 w-8 items-center justify-center"><Plus size={12} /></button></div></div><div className="text-right"><p className="text-[9px] text-slate-400">Estimated subtotal</p><b className="text-xl">{item.price == null ? "On request" : format(item.price * item.travellers, item.currency)}</b></div></div></div></article>)}</div>
          <aside className="sticky top-28 rounded-2xl border border-slate-100 bg-white p-6 shadow-[0_14px_40px_rgba(15,23,42,.08)]"><h2 className="text-lg font-black">Cart summary</h2><div className="mt-5 space-y-3 border-b border-slate-100 pb-5 text-xs">{cart.map((item) => <div key={item.id} className="flex justify-between gap-4"><span className="truncate text-slate-500">{item.title} × {item.travellers}</span><b>{item.price == null ? "—" : format(item.price * item.travellers, item.currency)}</b></div>)}</div><div className="mt-5 flex items-end justify-between"><span className="text-sm font-bold">Estimated total</span><b className="text-2xl">{new Intl.NumberFormat("en-US", { style: "currency", currency: code, maximumFractionDigits: 0 }).format(estimatedTotal)}</b></div><p className="mt-2 text-[10px] leading-4 text-slate-400">Final pricing, availability and payment are confirmed separately for each tour.</p><div className="mt-5 space-y-2">{cart.map((item) => <Link key={item.id} href={`/booking/${item.id}?adults=${item.travellers}`} className="group flex items-center justify-between rounded-xl bg-blue-600 px-4 py-3 text-xs font-bold text-white transition hover:bg-blue-700"><span className="truncate">Book {item.title}</span><ArrowRight size={14} className="shrink-0 transition group-hover:translate-x-1" /></Link>)}</div><p className="mt-5 flex items-center justify-center gap-2 text-[10px] font-semibold text-slate-500"><Shield size={13} className="text-emerald-600" />Secure booking and protected payments</p></aside></div>}
      </section>
    </main>
  );
}

function EmptyCart() { return <div className="mx-auto flex max-w-xl flex-col items-center py-24 text-center"><span className="flex h-20 w-20 items-center justify-center rounded-full bg-blue-50 text-blue-600"><Bag size={34} /></span><h2 className="mt-6 text-2xl font-black">Your cart is empty</h2><p className="mt-3 text-sm leading-6 text-slate-500">Add a tour to compare costs and continue to secure booking.</p><Link href="/tours" className="mt-7 flex items-center gap-2 rounded-xl bg-blue-600 px-7 py-3 text-sm font-bold text-white">Find your next tour <ArrowRight size={15} /></Link></div>; }
