export const pagePermissions: Record<string, string> = {
  "/dashboard": "dashboard.view",
  "/users": "users.view",
  "/roles": "roles.view",
  "/permissions": "permissions.view",
  "/settings": "settings.view",
  "/settings/countries": "countries.view",
  "/settings/cities": "cities.view",
  "/settings/payment": "settings.view",
  "/settings/api": "settings.view",
  "/email-templates": "email_templates.view",
  "/profile": "profile.view",
  "/customers": "customers.view",
  "/customers/[id]": "customers.view",
  "/suppliers": "suppliers.view",
  "/agents": "agents.view",
  "/affiliates": "affiliates.view",
  "/tours": "tours.view",
  "/tours/create": "tours.create",
  "/tours/[id]/edit": "tours.edit",
  "/tours/categories": "categories.view",
  "/tours/subcategories": "subcategories.view",
};
